name: weather_app
description: A simple Flutter weather app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  lottie: ^3.3.1
  intl: ^0.20.2
  country_picker: ^2.0.20
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics_presets: ^2.26.1
  dart_code_metrics: 4.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/background.json
    - assets/animations/animation2.json
    - assets/animations/animation3.json
    - assets/animations/animation4.json
    - assets/animations/Weather-snow.json
    - assets/animations/Foggy.json
    - assets/animations/Thunderstorm.json
    - assets/animations/little sun.json
    - assets/animations/rainy icon.json   
    - assets/animations/Clouds.json  
    - assets/animations/cloudy.jpg
    - assets/animations/sunny.jpg
    - assets/animations/snow.jpg